apache/cordova-lib

- cordova-lib/src/cordova/platform.js
CB-8227 CB8237 CB-8238
Add --save option to 'cordova platform add',
'cordova platform remove' and 'cordova platform update'
> CB-8227 CB-8237 CB-8238 Add --save option to 'cordova platform add', 'cordova platform remove' and 'cordova platform update'

- cordova-lib/src/cordova/metadata/firefoxos_parser.js
https://issues.apache.org/jira/browse/CB-8448
> CB-8448 add support for activities

- cordova-lib/src/plugman/registry/registry.js
> CB-8602 plugman: publish fail early if unsupported npm is active

- cordova-lib/src/cordova/restore-util.js
If `prepare` is called with no platforms specified, we prepare all installed platforms but don't restore any from `config.xml`. In this scenario, we should restore all platforms listed in `config.xml`.
> CB-8784 Prepare with no platforms should restore all platforms.

- cordova-lib/src/cordova/cordova.js
- cordova-lib/src/cordova/requirements.js
This is implementation for [CB-8898](https://issues.apache.org/jira/browse/CB-8898) which adds `requirements` module, used by CLI.
> CB-8898 Introduces `requirements` cordova module

- cordova-lib/src/cordova/superspawn.js
This fixes [CB-9073](https://issues.apache.org/jira/browse/CB-9073)
> CB-9073 Allow to add platform if project path contains `&` symbol

- cordova-lib/src/cordova/plugin.js
Adds logic to `plugin remove` to look up a plugin by "short name" if we don't find it by id. This means, for example, that you can use the following command:
cordova plugin remove camera
Instead of:
cordova plugin remove cordova-plugin-camera
Also removes a bunch of unecessary calls to `path.join(projectRoot, 'plugins')`, since we already have this path stored in a variable.
> CB-9065 Allow removing plugins by short name.

- cordova-lib/src/PluginInfo.js
Catch this scenario and display a useful message.
> CB-9188 Confusing error after delete plugin folder then prepare.

- cordova-lib/spec-plugman/fetch.spec.js
https://issues.apache.org/jira/browse/CB-9421
> CB-9421 Added a test for plugin fetch with searchpath parameter

- cordova-lib/src/cordova/prepare.js
- cordova-lib/src/plugman/prepare-browserify.js
This PR fixes https://issues.apache.org/jira/browse/CB-9549
It also includes https://github.com/apache/cordova-lib/pull/279
> CB-9549 Removes excess JS files from browserified app 

- cordova-lib/spec-plugman/uninstall.spec.js
- cordova-lib/src/plugman/install.js
- cordova-lib/src/plugman/util/PlatformJson.js
This fixes [CB-9556](https://issues.apache.org/jira/browse/CB-9556)
> CB-9556 Don't uninstall dependent plugin if it was installed as a top-level after

- cordova-lib/src/platforms/PlatformApiPoly.js
See [CB-9407](https://issues.apache.org/jira/browse/CB-9407) for details. This PR is an alternative to #274, reworked according to recent changes (PlatformApi).
> CB-9407 Fixes incorrect applying of plugin-provided config changes.

- cordova-lib/src/cordova/lazy_load.js
- cordova-lib/src/cordova/platform.js
The recommended method is to use `cordova platform add git_url#branch`.
> Removing the '--usegit' flag from `cordova platform`.

- cordova-lib/spec-plugman/fetch.spec.js
- cordova-lib/spec-plugman/plugins/recursivePlug/asset.txt
- cordova-lib/spec-plugman/plugins/recursivePlug/demo/config.xml
- cordova-lib/spec-plugman/plugins/recursivePlug/plugin.xml
- cordova-lib/src/plugman/fetch.js
Emit the error situation, and continue on using --link
> CB-8809 force --link use instead of recursive failure

- cordova-lib/src/cordova/platform.js
A fix for [CB-10432](https://issues.apache.org/jira/browse/CB-10432)
> CB-10432 Fix plugin installation for newly added platform

- cordova-common/spec/CordovaLogger.spec.js
- cordova-common/src/CordovaLogger.js
- cordova-lib/spec-cordova/fixtures/plugins/cordova-lib-test-plugin/LICENSE
- cordova-lib/spec-cordova/fixtures/plugins/cordova-lib-test-plugin/NOTICE
- cordova-lib/spec-cordova/fixtures/plugins/cordova-lib-test-plugin/package.json
- cordova-lib/spec-cordova/fixtures/plugins/cordova-lib-test-plugin/plugin.xml
- cordova-lib/spec-cordova/plugin.spec.js
[Jira issue](https://issues.apache.org/jira/browse/CB-10791)
> CB-10791 Add adjustLoggerLevel to cordova-common.CordovaLogger

- cordova-common/spec/util/xml-helpers.spec.js
- cordova-common/src/util/xml-helpers.js
> CB-10694 - Platform-specific configuration preferences don't override global settings

- cordova-lib/src/cordova/serve.js
* Make serve dashboard take config.xml -> content.src entry point into account
* Added redirection to the referer' platform content to resolve an URL against that platform www directory
[Jira issue](https://issues.apache.org/jira/browse/CB-11274)
> CB-11274 Platform browser: wrong path for config.xml

- cordova-lib/src/cordova/platform.js
[Jira issue](https://issues.apache.org/jira/browse/CB-11339)
> CB-11339 Add a warning about prerelease platform usage

- cordova-lib/spec-cordova/save.spec.js
JIRA issue [CB-11679](https://issues.apache.org/jira/browse/CB-11679)
> CB-11679 Speed up save/restore tests

- .gitignore
- integration-tests/pkgJson-restore.spec.js
- integration-tests/platform.spec.js
- integration-tests/save.spec.js
- src/cordova/platform/addHelper.js
- src/cordova/restore-util.js
> removed some circular deps, got some tests passing

- spec/cordova/platform/remove.spec.js
Added unit tests for remove platform
> CB-12361 : added unit tests for remove platform

- spec/cordova/platform/save.spec.js
> CB-12361 : added tests for save.js

- src/cordova/platform/index.js
Added deprecation warning for cordova platform save
> CB-13057 : added deprecation warning for cordova platform save

- src/cordova/platform/addHelper.js
Added deprecation notice for webos
> CB-13056 : added deprecation notice for webos

- src/plugman/plugman.js
n/a
fixes CB-13020: plugman filters out nohooks opt
manual
> CB-13020: (plugman) install filters out nohooks

- spec/cordova/plugin/search.spec.js
Added tests for plugin/search.js.
> CB-12361 : added tests for plugin/search.js

- spec/cordova/platform/list.spec.js
Added tests for platform/list.js
> CB-12361 : added tests for platform/list.js

- integration-tests/HooksRunner.spec.js
- spec/cordova/plugin/remove.spec.js
> CB-12361 : added plugin remove tests

- spec/cordova/plugin/index.spec.js
- src/cordova/plugin/index.js
Updated index.js and test to fix cordova plugin search
> CB-13288 : updated index.js and test to fix cordova plugin search

- spec/cordova/platform/check.spec.js
Added unit tests for check.js to increase coverage
> CB-12361 : added unit tests for check.js

- spec/cordova/platform/addHelper.spec.js
- src/cordova/platform/addHelper.js
include a check for pkgJson devDependencies
> :CB-13532 : updated to include a check for pkgJson devDependencies

- package.json
- spec/cordova/platform/check.spec.js
- spec/cordova/plugin/remove.spec.js
- spec/helper.js
- spec/helpers.js
Set of approved changes from #629
@brodybits
> Minor spec improvements

- integration-tests/pkgJson-restore.spec.js
This aligns the *code* of various specs with their respective *descriptions*.
> Honest specs in pkgJson-restore.spec

- integration-tests/pkgJson-restore.spec.js
> Avoid requireNoCache in pkgJson-restore.spec

- src/platforms/platformsConfig.json
This will remove a lot of noise during E2E tests.
> Update android platform to latest release

- integration-tests/pkgJson.spec.js
Only the `pkgJson.spec` part of #629 as requested by @brodybits. For further information see #629.
This commit does not drop any test cases. However, it fixes various bugs
in the existing expectations and often asserts stronger expectations
than the original tests.
Changes include:
- DRY code
- Improve formatting
- Reduce excessive comments
- Simplify platform list generation
- Wrap all tests in common describe to allow common setup/teardown
- Use a fresh tmpDir for every test to avoid caching issues
- Use fs-extra for setup/teardown
- FIX Wait for promise
- Properly set default timeout for the whole suite
- Don't symlink into fixtures
- Sane config file handling
- Remove event listeners on teardown
- Re-enable disabled test 005 that was fixed by #628
- Do not quote props when not needed …
> Cleanup pkgJson.spec

- integration-tests/pkgJson.spec.js
> Avoid requireNoCache in pkgJson.spec

- src/hooks/HooksRunner.js
Minor cleanup of the imports in HooksRunner.spec.
> Organize imports in HooksRunner.spec

- integration-tests/HooksRunner.spec.js
- package.json
- src/hooks/HooksRunner.js
This PR fixes and improves shebang extraction in HooksRunner.
This will fix a class of CI failures from #642.
> Fix shebang extraction in HooksRunner

- integration-tests/fetch.spec.js
Part of the spec speedup effort.
> fetch.spec: 30% shorter runtime by factoring out project setup

- package.json
See https://github.com/sindresorhus/read-chunk/pull/11
> Update read-chunk to properly close file descriptors on failure

- integration-tests/plugman_fetch.spec.js
- spec/common.js
- spec/cordova/cordova-lib.spec.js
- spec/cordova/emulate.spec.js
- spec/cordova/platform/addHelper.spec.js
- spec/cordova/platform/remove.spec.js
- spec/plugman/install.spec.js
The remaining fixes from #649 after #669 has been merged.
> Various spec fixes and cleanup

- integration-tests/pkgJson-restore.spec.js
- spec/cordova/restore-util.spec.js
- Runtime: 217s -> 2s (on my machine)
- No dependency on the network
- Easier tests
Test names and comments will still have to be edited a bit if we want to merge this, but I first wanted to know what you think about this change.
> Radically focused restore.spec finally fast and reliable

- integration-tests/platform.spec.js
- spec/cordova/create.spec.js
- spec/cordova/platforms/platforms.spec.js
- spec/plugman/add_platform.spec.js
- spec/plugman/create.spec.js
- spec/plugman/install.spec.js
Builds upon #674 since that's necessary to fix #673 too. Be sure to ignore white space for reviewing.
> One root `describe` per suite

- src/cordova/util.js
This also removes usage of Q-specific functionality (see #681)
> Remove unused npm utility functions

- integration-tests/plugman_uninstall.spec.js
- spec/cordova/platform/addHelper.spec.js
- spec/cordova/plugin/add.spec.js
- spec/cordova/prepare.spec.js
- spec/cordova/restore-util.spec.js
- spec/plugman/create.spec.js
- spec/plugman/install.spec.js
- src/hooks/Context.js
- src/plugman/platform.js
These are bits and pieces of off-topic changes that popped-up during the preparation or review of other PRs.
> Bits and pieces

- package.json
As agreed in: <https://lists.apache.org/thread.html/083ffe568bad2a8adc5533cbe5aca481bdd921e22a6aad9602aaded2@%3Cdev.cordova.apache.org%3E>
> Start 9.0.0-dev

- src/platforms/platformsConfig.json
none
- Update each platform config with a valid and active git URL.
none
> Updated Platform Config Git URL Paths

- .travis.yml
- appveyor.yml
Just some minor cleanup of our CI configs. Shallow clones on AppVeyor as a bonus.
> Minor cleanup of CI configs

- package.json
- src/plugman/createpackagejson.js
The existing code returned an instantly resolved promise despite the fact that it was doing async operations.
Promisified the async function and properly returned the resulting promise.
Manually tested this using the plugman CLI. Works like it should.
> Proper async code in plugman.createpackagejson

- src/plugman/createpackagejson.js
- src/plugman/init-defaults.js
This PR removes dead code from `plugman/createpackagejson` and `plugman/init-defaults` and simplifies the passing of arguments between the two.  There should be absolutely no change in behavior.
For further details please see the individual commits.
Manual testing using Plugman CLI
> Cleanup plugman.createPackageJson

- integration-tests/pkgJson.spec.js
- src/cordova/plugin/add.js
- src/cordova/plugin/list.js
- src/plugman/install.js
Just the tiniest of things that I stumbled upon during code reading. No functional changes.
> Minor code cleanup

- package.json
Update Testing Platform
Update jasmine from `^3.3.1` to `^3.5.0`.
- `npm t`
> chore: update jasmine dependencies

- integration-tests/plugman_fetch.spec.js
Just minor test cleanup plus fixing of a disabled test.
See commits for details
> plugman_fetch.spec cleanup

- integration-tests/fetch.spec.js
- integration-tests/pkgJson.spec.js
- integration-tests/plugman_uninstall.spec.js
- package-lock.json
- package.json
- spec/cordova/platform/addHelper.spec.js
- spec/cordova/util.spec.js
- spec/helpers.js
- spec/plugman/install.spec.js
- src/cordova/plugin/add.js
- src/hooks/Context.js
Use latest cordova eslint configs & applied automated fixes
- `npm t`
> chore: bump cordova-eslint w/ automatic fixes

- integration-tests/plugin.spec.js
Fixes a test that failed due to an updated dependency ([example test log](https://travis-ci.com/github/apache/cordova-lib/jobs/511151470#L913))
> test(plugin.spec): fix version change in test fixture

- spec/cordova/platform/addHelper.spec.js
- src/cordova/platform/addHelper.js
Improves code and tests related to the code fixed in #874.
> refactor(addHelper): more concise package.json spec lookup

- package-lock.json
- package.json
**Bumped Release Dependencies:**
- `execa@^5.1.1`
- `fs-extra@^10.0.0`
- `init-package-json@^2.0.5`
**Bumped Dev Packages:**
- `delay@^5.0.0`
- `jasmine@^3.10.0`
**Other Changes:**
- Rebuilt `package-lock.json`
This PR does not update ESLint because it will require a bit of code changes. Will be handled in a separate PR.
- `npm t`
> dep!: update dependencies

- package-lock.json
Keep package-lock up to date
Delete and rebuild `package-lock.json`
- `npm t`
> chore: rebuild package-lock

- package-lock.json
- package.json
n/a
* Use latest cordova-fetch
* Rebuild package-lock
* Updated cordova-fetch@3.1.0
* Rebuilt package-lock
n/a
> dep(npm): bump cordova-fetch@3.1.0 w/ package-lock rebuild

- package-lock.json
- package.json
n/a
prepare for next major release
bump package version & package-lock version to `12.0.0-dev`
n/a
> chore: prepare package version for next major 12.0.0-dev

- .github/workflows/ci.yml
n/a
* Drop deprecatetd node version 
* Add latettst node versions
* Update GH Action dependencies
* Drop node 12 & 14
* Add node 16 & 18
* Bump Action Deps.
* `actions/checkout@v3`
* `actions/setup-node@v3`
* `codecov/codecov-action@v3`
n/a
> ci(workflow): update node support & action dependencies

- integration-tests/pkgJson.spec.js
n/a
Temporary disable broken test spec 12.
Disabled test.
n/a
> test: temporary disable broken spec#012

- .github/workflows/ci.yml
> ci(workflow): update codecov action usage

- spec/cordova/fixtures/plugins/com.plugin.withhooks/scripts/beforeBuild.sh
- spec/cordova/fixtures/projectHooks/android/appAndroidBeforeBuild.sh
- spec/cordova/fixtures/projectHooks/appBeforeBuild1.sh
Please squash when merging! @erisu 
All
Tests were failing in node 18
Add the hashbang `#!/bin/sh` line to shell hook scripts
All test passing in node 18 now
> fix(node-18): hook tests

- package-lock.json
- package.json
n/a
Bump all possible packages for next major
**Bumped Following Packages**
- [cordova-common@5.0.0](https://github.com/apache/cordova-lib/commit/239facfe85427b7e918d88a610020f47742f61fb)
- [cordova-fetch@4.0.0](https://github.com/apache/cordova-lib/commit/a36aeb438ec49b3af1eba45bb04b3a2b5c3ece36)
- [bump init-package-json@5.0.0](https://github.com/apache/cordova-lib/commit/20ad14b38918a245f711019738b8db4903524756)
- [jasmine@4.6.0](https://github.com/apache/cordova-lib/commit/d997917c66e2b3cad81b4fd70833efc5cae52cf5)
- [semver@7.5.0](https://github.com/apache/cordova-lib/commit/7b05f632d933c5a9526ea86896bb3ae53aa06d37)
- [cordova-serve@4.0.1](https://github.com/apache/cordova-lib/commit/d6c6270558372be0382af91a7e3feec42682021a)
**Other**
- [rebuilt …
> dep!: bump all possible packages

- package-lock.json
- package.json
- spec/cordova/prepare.spec.js
- spec/helpers.js
- src/cordova/cordova.js
- src/cordova/platform/getPlatformDetailsFromDir.js
- src/cordova/plugin/add.js
- src/cordova/project_metadata.js
- src/hooks/scriptsFinder.js
- src/plugman/fetch.js
- src/plugman/install.js
- src/plugman/uninstall.js
- src/plugman/util/dependencies.js
n/a
Bump eslint for next major
- [bump @cordova/eslint-config@latest@5.0.0 w/ automatic fix](https://github.com/apache/cordova-lib/commit/e0d8b809b003964d00a25dab04143dfcf5d03905)
Includes automatic lint corrections and package-lock rebuild.
`npm t`
> dep!: bump @cordova/eslint-config@latest@5.0.0 w/ automatic fix

- .github/workflows/release-audit.yml
- .ratignore
- licence_checker.yml
n/a
check license header and package dependency licenses during commit and pr submission
create release audit workflow
n/a
> ci(release-audit): add license header and dependency checker

- package-lock.json
- package.json
Bump package to next major for breaking changes
Bump package to 13.0.0-dev
- `npm t`
> chore: bump 13.0.0-dev

- .gitignore
- package-lock.json
- package.json
- spec/cordova/util.spec.js
n/a
Update npm dependencies
Bumped:
- cordova-common@6.0.0
- jasmine@5.9.0
- cordova-android@13.0.0
Additional:
- Replaced `nyc` with `c8`
- Rebuilt `package-lock.json`
- `npm t`
> chore(npm)!: bump various packages

- .asf.yaml
- .gitattributes
- .gitignore
- .npmignore
- .npmrc
- .ratignore
- CONTRIBUTING.md
- README.md
- RELEASENOTES.md
- cordova-lib.js
n/a
Update root files
- Added missing license headers
- Formatting of license headers
- Clean & improve git ignore files
- Ignore more files during npm pack
- Clean up rat ignore
- Remove more deprecated platforms from git attributes
`npm t`
> chore: various updates to the root files
