apache/cordova-lib

cordova-lib/src/configparser/ConfigParser.js
cordova-lib/src/cordova/platform.js
cordova-lib/src/cordova/restore-util.js

CB-8482: Update engine syntax within config.xml
- from : `<cdv:engine id="android" version="3.7.0-dev" />`
- to :      `<engine name="android" version="3.7.0-dev" />`
- updated and tested all modules that depended on old syntax

CB-8482: Update engine syntax within config.xml

---

cordova-lib/src/cordova/platform.js

CB-8633 BugFix: Support for `urls to tarballs` was broken

CB-8633 BugFix: Support for urls to tarballs was broken

---

cordova-lib/src/plugman/platforms/ios.js

I have an iOS project named `Foo & Bar`. When trying to run `cordova plugin add <anything>` an error is thrown:
```
Failed to install 'org.apache.cordova.splashscreen':CordovaError: could not find -Info.plist file, or config.xml file.
at Object.module.exports.parseProjectFile (/Users/casey/projects/example/node_modules/cordova/node_modules/cordova-lib/src/plugman/platforms/ios.js:193:19)
at Object.ActionStack.process (/Users/casey/projects/example/node_modules/cordova/node_modules/cordova-lib/src/plugman/util/action-stack.js:55:49)
at handleInstall (/Users/casey/projects/example/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:575:20)
at /Users/casey/projects/example/node_modules/cordova/node_modules/cordova-lib/src/plugman/install.js:335:28
at _fulfilled …
```

Fix plugman install failure on iOS containing &

---

cordova-lib/src/util/windows/jsprojManager.js

On jsprojManager.js we currently don't have UAP as TargetPlatformIdentifier. We should have UAP as a TargetPlatformIdentifier and treat it as windows.

CB-8791 Recognize UAP as a valid TargetPlatformIdentifier

---

cordova-lib/src/cordova/compile.js
cordova-lib/src/cordova/emulate.js
cordova-lib/src/cordova/platform.js
cordova-lib/src/cordova/run.js
cordova-lib/src/cordova/superspawn.js
cordova-lib/src/cordova/targets.js
cordova-lib/src/plugman/install.js
cordova-lib/src/plugman/uninstall.js

Modifies superspawn to support a "chmod" option. When truthy, attempts to set the target file mode to 755 before executing.  Specifies this argument as truthy for common CLI operations (compile, run, and steps in plugman).  Didn't add it for hooks runner since that particular mode is in legacy support.

CB-9030: Shell scripts can't execute when pulled from Windows to *nix via source control

---

cordova-lib/src/cordova/platform.js

To avoid attempting to add a plugin twice while adding a platform (a scenario that can occur now with automatic restore of plugins and platforms), when adding plugins to a newly added platform we check to see if the plugin has already been added, by calling plugman's `PlatformJson.isPluginInstalled()`, which looks in `plugins/<platform>.json` to see if the plugin has been installed for a platform.
If you delete a platform's folder from the platforms folder, it's `plugins/<platform>.json` file still exists, so if you add the platform again, we think all plugins are already installed for it and don't try to install them.
Simple fix is to delete the platform's `plugins/<platform>.json` file before adding a platform, so we start with a clean slate.

CB-9051 Plugins don't get re-added if platforms folder deleted.

---

cordova-lib/src/cordova/platformsConfig.json

Updates the Android pinned version for Cordova 4.3.x to 3.7.2, which contains the recent security patch.

Updated Android pinned version to 3.7.2 (security patch).

---

cordova-lib/spec-plugman/platforms/android.spec.js
cordova-lib/spec-plugman/platforms/common.spec.js

Two tests fail on Windows in a non-admin command window because they rely on creating symlinks. Since creating the symlinks isn't the purpose of the test but just setup for the test, if that fails and the platform is `win32`, we now just bail on the test.
Another test failed because a folder unexpectedly exists when run from a non-admin prompt. I'm not 100% sure why the folder exists, but the test was bogus... the test actually ends up testing that we throw if `src` does not exist, which is something that we verify in an earlier test, while the intent of the test was to verify we throw if `dest` *already* exists. Since it is `copyNewFile()` that is supposed to throw in that scenario, so I updated the test to check for that.
Finally, a fourth test failed on Windows (admin or non-admin) …

Fix four failing tests on Windows.

---

cordova-lib/src/cordova/lazy_load.js
cordova-lib/src/cordova/util.js

Adding a platform using a version range didn't work with `--usegit`, since it would try to use that version range as a git tag. This was a problem if you added the platform using `platform add <platform>@<range>`, and also because our pinned platforms now use tilde versions (which are shorthand for a version range).
Fix is to use `npm view` to find the most recent version that matches the range, and use that.
We need to do the same when installing from npm, when we do our check to see if the requested version has previously been downloaded using git.

CB-9108 Handle version ranges when add platform with --usegit.

---

cordova-serve/.jshintrc
cordova-serve/README.md
cordova-serve/RELEASENOTES.md
cordova-serve/package.json
cordova-serve/serve.js
cordova-serve/src/browser.js
cordova-serve/src/exec.js
cordova-serve/src/platform.js
cordova-serve/src/server.js
cordova-serve/src/stream.js
cordova-serve/src/util.js

This takes code and functionality from `cordova-browser` and `cordova-lib` (`cordova serve` command) and combines it in a single module. There's a lot of code here, but by far the bulk of it comes directly from those two places. See readme.md for more information.
Once this is checked in, I will:
* Update COHO release tools to work with this module.
* Work to get a `cordova-serve` release out.
* Update `cordova-lib` and `cordova-browser` to use `cordova-serve`.

CB-9127 Implements cordova-serve module.

---

cordova-lib/src/cordova/lazy_load.js
cordova-lib/src/cordova/plugin.js
cordova-lib/src/plugman/registry/registry.js

It adds the very latest version rather than the latest matching version.
Internally we are using a version of `npm` that doesn't understand caret versions, so it just gets the latest. I missed this previously because when I tried this, the latest version **was also** the latest matching version.
The same problem also applies to plugins.
I've made a slightly different fix in each case:
For platforms, we already had the latest matching version as a result of our call to `getLatestMatchingNpmVersion()`, so I just use that.
For plugins, in this specific scenario (a caret version) I turn it into a standard range using a version of `semver` that understands caret ranges (so `^1.2.3` becomes `>=1.2.3 <2.0.0`) and use that instead.
Note that this is currently an issue with platforms and plugin …

CB-9147 Adding a platform via caret version adds wrong version

---

cordova-lib/src/plugman/create.js
cordova-lib/src/plugman/platform.js
cordova-lib/src/plugman/util/strip-license.js
cordova-lib/templates/base.js
cordova-lib/templates/platforms/android/android.xml
cordova-lib/templates/platforms/android/base.java
cordova-lib/templates/platforms/ios/ios.xml

Also, updates code that uses the template files when building plugins to strip the license so its not included in users' projects (note we don't need to strip the license from the XML files as we immediately generate an element tree with `ElementTree`).

Adds license headers to files in templates folder.

---

cordova-lib/src/cordova/platform.js
cordova-lib/src/cordova/plugin.js

Also ensures `platform save` saves version with tilde.

CB-9177 Use tilde instead of caret when save to config.xml.

---

cordova-serve/src/browser.js

Note that this requires a fairly recent Windows 10 build (`10166` or later for Edge to support `localhost`, and probably around `10158` or later for the command line launch of Edge to work).

Add support for --target=edge to launch app in Edge browser.

---

appveyor.yml

This fixes Appveyor build failure, introduced by https://github.com/apache/cordova-js/commit/eb620e2934e2d6706e71a2f8957343935d6dcf32

CB-9291 Fixes Appveyor build failure

---

cordova-lib/src/gitclone.js
cordova-lib/src/plugman/fetch.js

actually checkout git_ref because it may be a branch OR a commit SHA
This functionality was lost when CB-8908 was implemented.
The fix will still clone with depth=1 IF a branch or a commit sha was not specified.

CB-9384 Plugman should be able to checkout a commit SHA

---

cordova-serve/src/stream.js

Switched to using `Cache-Control` value of `no-store` instead of `no-cache`.

CB-9545 Cordova-serve's 'noCache' option does not work in IE.

---

cordova-serve/src/platform.js

The `servePlatform()` method provided by `cordova-serve` figures out the project and platform root directories (either from the cwd or a provided path). Since this information is potentially useful to the caller, it is now provided in the return value.

CB-9546 cordova-serve.servePlatform() should provide project folders

---

cordova-lib/src/plugman/prepare-browserify.js

This PR solves problem with a lot of plugins, which uses `js-module` tags with `merges target=""`. Such modules are not loaded correctly, so, for example, plugin proxies on windows platform are not available at runtime.
Instead of injecting `modulemapper` methods and `require` calls into bundle, this PR assumes that bundled plugins modules will be loaded by special 'browserify' version of `cordova/pluginloader` (see https://github.com/MSOpenTech/cordova-js/blob/CB-9505/src/common/pluginloader_b.js)
This fixes https://issues.apache.org/jira/browse/CB-9505
This PR needs to be merged along with corresponding PR to cordova-js: https://github.com/apache/cordova-js/pull/126

CB-9505 Correct plugin modules loading within browserify flow

---

cordova-lib/src/plugman/registry/registry.js

When Cordova used `npm 1.3.x` internally, we had to process "caret versions" since `npm 1.3.x` didn't understand them. As part of that, we'd turn the caret version into a fully defined version range, which contained a space, and `npm 1.3.x` required that we wrap such a range in quotes.
This logic broke when we upgraded to `npm 2.10.x` - it no longer requires the quotes in this scenario, and in fact fails if we include them. However, we also no longer need to do this processing (since `npm 2.10.x` understands caret versions), so we can just remove that code altogether.

CB-9559 Adding a plugin with caret in version results in an error

---

cordova-lib/src/platforms/PlatformApiPoly.js

Don't try to create `ConfigParser()` in `PlatformApiPoly` constructor, since we may not have copied the `config.xml` file into place yet. Instead, create it once we know we have the `config.xml` file.

CB-9604 Fix error adding browser platform with PlatformApi polyfill.

---

cordova-lib/src/cordova/plugin.js

This fixes [CB-9617](https://issues.apache.org/jira/browse/CB-9617)
The cause of problem is that `plugman.prepare` functionality was eliminated (since the new flow assumes that plugin installation is totally handled by `PlatformApi` instance) and plugin's assets and js-files are now get copied into app's `www` folder by `PlatforfmApi.prepare`.
Due to this at the time after _plugin installation_ and before _prepare_ the platform folder might exist in incorrect state.

CB-9617 Fixes incorrect project state after adding/removing plugins

---

cordova-lib/src/util/windows/jsprojManager.js

https://issues.apache.org/jira/browse/CB-9601
Adds logic to convert Windows specific four-digits version to three-digits semver compatible version.

CB-9601 Fix <framework>.versions support on Windows after semver update

---

cordova-lib/spec-cordova/ConfigParser.spec.js
cordova-lib/src/configparser/ConfigParser.js
cordova-lib/src/cordova/plugin.js

This fixes [CB-9631](https://issues.apache.org/jira/browse/CB-9631)
The idea is that we need to save installed plugins to config.xml only if installation succeeds (similar to platform save)

CB-9631 Save plugin to config.xml only if installation succeeds

---

cordova-lib/spec-cordova/ConfigParser.spec.js
cordova-lib/spec-cordova/metadata/ios_parser.spec.js
cordova-lib/spec-cordova/test-config.xml
cordova-lib/src/configparser/ConfigParser.js
cordova-lib/src/cordova/metadata/ios_parser.js

Tests are included as well. &lt;access&gt; and &lt;allow-navigation&gt; tags have two new attributes to account for ATS: `minimum-tls-version` (defaults to 'TLSv1.2') and `requires-forward-secrecy` (defaults to 'true').
If the defaults are set, there will be *no* corresponding entry in ATS, to reduce verbosity in the Info.plist.

CB-9569 - Support <access> and <allow-navigation> tag translation to Application Transport Security (ATS) Info.plist directives

---

cordova-lib/src/cordova/create.js

I could repro the issue using npm@3.3.6 as npm@3.3.5 seems to have issues with Cordova installation.
Requires [cordova-app-hello-world#14](https://github.com/apache/cordova-app-hello-world/pull/14) changes in order for require to work.
[Jira issue](https://issues.apache.org/jira/browse/CB-9712)

CB-9712 CLI 5.3 breaks with node 3.3.3

---

cordova-serve/package.json
cordova-serve/src/browser.js

Do this to avoid dialog that pops up on Windows if browser is not installed, and provide more meaningful error messages.

On Windows, verify browsers installed before launching.

---

cordova-lib/src/cordova/metadata/android_parser.js

Removes the old package name after the new one is created. If the package
name is different

CB-9736 - Extra main activity generated when an android package name specified

---

cordova-lib/src/cordova/restore-util.js

Cordova in a couple places was mis-using the Q.all() function from
the Q promises library. That function expects an array (of values or
promises), but Cordova was passing a single string parameter. The
string was actually being reduced like an array. Previously that
happened to work out OK: the result was an array of fulfilled
single-character promises. But one line of code in Q that worked
on node.js v4 now fails on node.js v5, where because of the bad
parameter it ends up assigning a value to an index of the string:
exception in cordova-lib\node_modules\q\q.js:1490
>    promises[index] = value;
TypeError: Cannot assign to read only property '0' of <string>
It appears the newer version of V8 is a little more strict about
assigning to a string index.
The fix is simply to use Q() instead …

CB-9935: Cordova CLI silently fails on node.js v5

---

cordova-lib/src/cordova/prepare.js
cordova-lib/src/hooks/HooksRunner.js

This PR adds an temporary polyfill for windows 'pre_package' event to keep compatibility with plugins, which uses this hook. It also adds a notice about 'pre_package' hook removal in next windows platform versions.
For more details on this see [corresponding mailing list discussion](http://apache.markmail.org/thread/enzm34cktoeqh4ss)

CB-10193 Add deprecation notice about pre_package removal

---

cordova-lib/spec-cordova/emulate.spec.js
cordova-lib/src/cordova/emulate.js

This fixes incorrect behaviour of `cordova emulate` command, which results in restoring all saved platforms even when only particular platform specified.
See [CB-10465](https://issues.apache.org/jira/browse/CB-10465) for details

CB-10465 Pass correct options to prepare from compile

---

cordova-common/cordova-common.js
cordova-common/package.json
cordova-common/spec/CordovaLogger.spec.js
cordova-common/src/CordovaLogger.js

This is an implementation for [CB-10176](https://issues.apache.org/jira/browse/CB-10176)
This PR adds a standard logger implementation, that could be reused by cli and platforms.

CB-10176 Adds standard logger, based on logger module from cordova-cli

---

.travis.yml
README.md
appveyor.yml
cordova-lib/package.json

This PR adds integration with codecov.io
There is also a few improvements for Travis and Appveyor configs and npm tasks:
* Simplify Travis and Appveyor configs by using relative `npm link`s
* Run `cordova-common` tests as a part of `test_script` (was the part of `install`)
* Shorten `npm run` scripts specification by assuming that tools are already in `PATH`(proof: https://docs.npmjs.com/cli/run-script)

CB-10531 Enable coverage reports for cordova-lib

---

cordova-lib/src/plugman/install.js

The framework tag was not being handled during plugin-install for Android. In the conditional check, it checks for the string literal 'platform' instead of just the platform.

CB-10553 Fix framework tag handler for Android

---

cordova-lib/src/cordova/run.js

JIRA [CB-10567](https://issues.apache.org/jira/browse/CB-10567)
This PR fixes the case when `cordova.raw.run()` promise always being resolved, event if run itself fails due to some reason.

CB-10567 Bubble up `cordova.raw.run()` error to the caller

---

cordova-lib/spec-cordova/platform.spec.js
cordova-lib/src/cordova/platform.js

This is a fix for [CB-10641](https://issues.apache.org/jira/browse/CB-10641) and [CB-10586](https://issues.apache.org/jira/browse/CB-10586)
This PR changes order of operations in `cordova.raw.platform('add', ...)` method so `cordova.raw.prepare` is called after all plugins installed into platform. Also apart from resolving the issue above, the new flow (`platform_add -> install_plugins -> prepare`) looks semantically more correct.

CB-10641 Run prepare _after_ plugins were installed

---

cordova-lib/spec-cordova/build.spec.js
cordova-lib/spec-cordova/compile.spec.js
cordova-lib/spec-cordova/emulate.spec.js
cordova-lib/spec-cordova/prepare.spec.js
cordova-lib/src/cordova/build.js
cordova-lib/src/cordova/clean.js
cordova-lib/src/cordova/compile.js
cordova-lib/src/cordova/emulate.js
cordova-lib/src/cordova/platform.js
cordova-lib/src/cordova/plugin.js
cordova-lib/src/cordova/prepare.js
cordova-lib/src/cordova/requirements.js
cordova-lib/src/cordova/run.js
cordova-lib/src/cordova/serve.js

This is a fix for [CB-10519](https://issues.apache.org/jira/browse/CB-10519)
This PR fixes the issue when promise returned from `cordova.raw` API would never be rejected if command is ran outside of cordova project. Instead synchronous exception will be thrown (by `util.preProcessOptions`), which is definitely unexpected for promise based API.
There are many indentation changes in this PR, so it's more convenient to review with [`?w=1`](https://github.com/apache/cordova-lib/pull/384?w=1) option

CB-10519 Wrap all sync calls inside of `cordova.raw` methods into promises

---

cordova-lib/src/plugman/platforms/browser.js
cordova-lib/src/plugman/platforms/common.js
cordova-lib/src/plugman/platforms/firefoxos.js
cordova-lib/src/plugman/platforms/webos.js

JIRA: [CB-10662](https://issues.apache.org/jira/browse/CB-10662)
This change is needed because some platforms (`browser` in particular)  doesn't contain own `config.xml` and rely on cordova, which generates one from defaults during `prepare`. However, prepare now called after plugin installation (after b04db5feaf5516836c8a157cc3331b75d6dca0eb) and hence fails due to abscence of config.

CB-10662 Use project's config.xml as a fallback for package name

---

cordova-lib/src/plugman/install.js
cordova-lib/src/plugman/uninstall.js

JIRA: https://issues.apache.org/jira/browse/CB-10708
This forces plugman to install plugin's www files to `platform_www` directory instead of `www` (see also https://github.com/apache/cordova-lib/pull/360 for background) when cordova CLI project detected. This allows to install plugins for each platform separately.

CB-10708 Install/uninstall plugins correctly into CLI project using plugman

---

cordova-lib/spec-cordova/save.spec.js
cordova-lib/src/cordova/restore-util.js

This PR updates plugin restore logic to restore plugins that were added to plugin.xml without `spec` attribute. See [CB-10761](https://issues.apache.org/jira/browse/CB-10761) for details

CB-10761 Resore plugins saved without spec attribute

---

cordova-lib/spec-cordova/platform.spec.js

This PR fixes test failure on nightly version, caused by pinned platform version, that is not yet released. See [CB-11337](https://issues.apache.org/jira/browse/CB-11337) for details and error message

CB-11337 Use latest released platform version in e2e tests

---

cordova-lib/spec-cordova/emulate.spec.js
cordova-lib/spec-cordova/run.spec.js
cordova-lib/src/cordova/emulate.js
cordova-lib/src/cordova/run.js

This PR moves handling of `--nobuild` option to CLI. CLI previously has delegated this logic to platform's
`run` method but since introducing `before_deploy` hook we call platform's `build` and `run` separately and now need to handle this option here.
JIRA issue: [CB-11652](https://issues.apache.org/jira/browse/CB-11652)

CB-11652 Update run and emulate to skip build

---

cordova-lib/spec-cordova/lazy_load.spec.js
cordova-lib/spec-cordova/util.spec.js
cordova-lib/src/cordova/lazy_load.js
cordova-lib/src/cordova/remote_load.js
cordova-lib/src/cordova/util.js
cordova-lib/src/plugman/registry/registry.js
cordova-lib/src/util/npm-helper.js

Before calling `npm cache add` when installing a platform or plugin, look for an existing `package.tgz` file in the cache directory. This avoids unnecessary `npm` call with long timeout if not connected to the internet.
Background: First time build failures in Cordova tools in Visual Studio are primarily due to `npm` failures. Therefore we are working to avoid any requirement for `npm` to hit the internet in simple build scenarios. This includes pre-installing cached versions of certain platforms and plugins. But we only get the full benefit if Cordova uses these cached versions if it finds them, without calling npm cache add.
A couple of things to note:
* This change uses shared code for platforms and plugins, and means plugins will also be cached to the `.cordova` directory rather than …

CB-11985 Check if cached platform/plugin exists before 'npm cache'

---

.gitignore
cordova-serve/src/server.js

All
With this change, cordova-serve includes the project root as an additional root for static routing. This is the final piece a middleware, so will only be utilized when a file isn't found through other means (the default static routing which points to the platform root, or other middleware that may have been injected by a third party).
This can be useful in cases where source files that have been transpiled (such as TypeScript files) are located under the project root on a path that mirrors the the transpiled file's path under the platform root, and is pointed to by a map file (otherwise when debugging in a browser, the browser won't be able to find the original source file).
Verified is resolved the problem reported in the bug, and lets you debug using original TypeScript sources in a …

CB-12284 Include project root as additional root for static router

---

cordova-lib/src/plugman/browserify.js

Define parent object first
[Jira issue](https://issues.apache.org/jira/browse/CB-12383)
Tested on windows and android with this code:
```
onDeviceReady: function() {
this.receivedEvent('deviceready');
navigator.notification.alert(cordova.require("cordova/plugin_list").metadata);
},
```
Makes `require("cordova/plugin_list").metadata` also available with browserify.
Manual tests, run cordova-lib auto tests

CB-12383 Fix cordova_plugins metadata definition

---

cordova-common/spec/superspawn.spec.js
cordova-common/src/superspawn.js

Please review @stevengill and @audreyso. 
All.
This solves [CB-12557](https://issues.apache.org/jira/browse/CB-12557).
Some programs pump output to both stdout and stderr when exit codes are non-zero (i.e. `android`). It would be nice to get access to both streams in the reject handler.
In particular, to solve the suite of new issues arising from the updated Android SDK Tools in 25.3.1 ([CB-12554](https://issues.apache.org/jira/browse/CB-12554)), we need to detect when the `android` command exits with a non-zero status code _and_ contains particular language in `stdout`. This change to `superspawn` allows for that level of introspection.
Ran `npm test` on master branch, all tests pass. Then ran `npm test` on this branch, which includes a new test covering this case, all tests pass. …

CB-12557: superspawn now returns both stdout and stderr in reject handler

---

cordova-lib/spec-plugman/install.spec.js
cordova-lib/spec-plugman/plugins/dependencies/README.md
cordova-lib/spec-plugman/plugins/dependencies/Test4/package.json
cordova-lib/spec-plugman/plugins/dependencies/Test4/plugin.xml
cordova-lib/spec-plugman/plugins/dependencies/Test4/src/android/Test4.java
cordova-lib/spec-plugman/plugins/dependencies/Test4/www/plugin-test.js
cordova-lib/src/plugman/install.js

all
Fixes a problem described here:
https://issues.apache.org/jira/browse/CB-12606
In short, cordova fails to cope with already installed plugin dependency, if this dependency is of version with "-dev" suffix.
Manually tested on Windows with Android platform. Added an automated test.

CB-12606 Fix plugin dependency installation

---

cordova-lib/src/cordova/plugin.js

CB-12773: fixed incorrect plugin version fetching issue

---

spec-cordova/prepare.spec.js
src/cordova/prepare.js

Add unit tests for prepare.js in prepare.spec.js. 
npm run cover lists prepare.js at 97.4

CB-12361: Added unit tests for prepare.js

---

integration-tests/plugman_uninstall.spec.js
src/plugman/browserify.js

all
https://issues.apache.org/jira/browse/CB-6143
Changes remaining `plugman.emit()` calls to `events.emit()` for consistency and to fix a build error when building a browserified app.
`npm test`, built an android app, built a browserified android app

CB-6143: Change plugman.emit() to events.emit()

---

spec/cordova/platform/getPlatformDetailsFromDir.spec.js

added unit-tests for getPlatformDetailsFromDir

CB-12361 : added unit-tests for getPlatformDetailsFromDir

---

integration-tests/HooksRunner.spec.js
spec/cordova/plugin/save.spec.js

added tests for plugin/save.js

CB-12361 : added tests for plugin/save.js

---

integration-tests/pkgJson-restore.spec.js
src/cordova/restore-util.js

Prevent package.json update with --nosave (for plugins)

CB-13463 : prevent package.json update with --nosave (for plugins)

---

.travis.yml
appveyor.yml
package.json
spec/cordova/util.spec.js
src/cordova/plugin/add.js

Added support for node 8 and fixed eslint error

CB-13501 : added support for node 8 and cleaned up eslint

---

package.json
spec/cordova/platform/addHelper.spec.js
spec/cordova/platform/remove.spec.js
spec/cordova/plugin/add.spec.js
spec/cordova/plugin/remove.spec.js
src/cordova/platform/addHelper.js
src/cordova/platform/remove.js
src/cordova/plugin/add.js
src/cordova/plugin/remove.js
src/cordova/restore-util.js

CB-12810 : keep existing formatting in package.json and fix eslint errors

---

.travis.yml
appveyor.yml
package.json

Also removed before_install from Travis configuration since Node 6 already comes with npm 3 there.

CB-14065: Drop support for Node 4 and add Node 10 to CI

---

spec/cordova/plugin/add.spec.js
src/cordova/plugin/add.js

All
Find and allow restoring plugins when they are located in package.json's devDependencies rather than dependencies.
The same change was already made for platforms: https://github.com/apache/cordova-lib/pull/607
Tested restoring plugins in a project with all cordova-related modules under devDependencies.

CB-13532: Find plugins in devDependencies

---

appveyor.yml
integration-tests/HooksRunner.spec.js
package.json

These tests tended to cause spurious fails on CI. After having done a complete cleanup, I don't find it surprising at all. I hope they are stable now.
Noteworthy changes include:
- Reset test files before each test
- Don't disguise setup/teardown as tests
- Compare objects instead of JSON strings
- Don't use reserved words as variable names
- Drop some duplicated/obsolete tests
- Fix linting errors
- Remove shelljs usage
- DRY and simplify code
- 200 LOC less

Clean up messy HooksRunner tests

---

src/plugman/plugman.js

This should resolve the issues brought up in [these comments](https://github.com/apache/cordova-lib/commit/474a33bebdf30b73ad5067bcf94fec55027c4155#r29314973)
Should go in to the next patch release

Set the fetch option to true in plugman

---

integration-tests/pkgJson-restore.spec.js

One test in pkgJson-restore.spec did NOT wait for the promise returned
by `prepare` to be resolved before continuing with other tasks.
Especially on Windows this could lead to EBUSY failures during cleanup
and in turn to failures during following tests.
Note: The order of `emptyPlatformList()` and `prepare()` does not seem to matter. Thus I chose the variant that was used throughout all other tests.

restore.spec: Wait for prepare promise to resolve

---

integration-tests/HooksRunner.spec.js
integration-tests/fetch.spec.js
integration-tests/pkgJson-restore.spec.js
integration-tests/pkgJson.spec.js
integration-tests/platform.spec.js
integration-tests/plugin.spec.js
integration-tests/plugman_fetch.spec.js
integration-tests/plugman_uninstall.spec.js
spec/cordova/platform/addHelper.spec.js
spec/cordova/platform/check.spec.js
spec/cordova/platform/remove.spec.js
src/cordova/platform/addHelper.js
src/cordova/platform/remove.js
src/cordova/plugin/add.js
src/cordova/prepare.js
src/cordova/restore-util.js
src/plugman/fetch.js
src/plugman/plugman.js
src/plugman/uninstall.js

Manual constant folding assuming any `fetch` options to be `true`.
Extends #617

CB-13055 Fold all fetch options to `true`

---

spec/cordova/plugin/remove.spec.js
src/cordova/plugin/remove.js

Fix promise handling when removing multiple plugins.
Ran existing automated tests. Wrote regression test.

Fix promise handling when removing multiple plugins

---

src/cordova/plugin/add.js

This affects how plugins are added for both Android and IOS.
This PR fixes CB-14243. Cordova-lib is ignoring save-exact b/c the wrong key name is being used to reference it in the options object that is propagated from cli.js.
Unit tests have been run and are passing.
✅Reported an issue in the JIRA database
✅Commit message follows the format: "CB-14243: {message}"
✅ Unit Tests pass

CB-14243: change dash to underscore for save-exact key reference

---

integration-tests/pkgJson-restore.spec.js

Only the `pkgJson-restore.spec` part of #629 as requested by @brodybits. See #629 for a full description.

Cleanup pkgJson-restore.spec

---

.gitignore
package.json

Make coverage script consider e2e tests too

---

package.json

A change in Jasmine 3.2 seems to be responsible for the recent CI failures. Pinning it to 3.1 for now.
See https://github.com/apache/cordova-ios/issues/393, https://github.com/jasmine/jasmine/issues/1590 and #636

Pin Jasmine to 3.1 to work around Promise issues

---

spec/cordova/build.spec.js
spec/cordova/platforms/platforms.spec.js
src/platforms/platformsConfig.json

All
- Remove nonsense "www" platform from listing in `cordova platform ls`
- Verify proper attributes and behavior of `platforms` object
- Verified that the nonsense "www" member is removed in spec
- Verified working properly in local copy of `cordova-lib` and `cordova-cli` projects
- __Verified__ that `npm test` completely passes (in CI)

CB-14148 remove nonsense "www" platform from Cordova listing

---

spec/helpers.js

Previously, the timeout defined by `setDefaultTimeout` did not apply for
`beforeAll` and `afterAll` blocks. This change fixes that.
The new implementation makes use of the fact that Jasmine processes
`beforeAll` in FIFO order and `afterAll` in LIFO order.
This should fix the failing tests for #640.

Fix setDefaultTimeout for beforeAll and afterAll

---

integration-tests/HooksRunner.spec.js

Test 012 sporadically takes slightly longer than the current default
timeout of 10s, so this increases the timeout for this test to 20s.

Fix sporadic timeout of HooksRunner test 012

---

integration-tests/plugman_uninstall.spec.js

Apart from a much-needed general cleanup of `plugman_uninstall.spec`, this fixes one of the tests disabled in e878ecb0b8860c36c59af18d158c89f48528fc9c as part of #613.

plugman_uninstall.spec cleanup

---

src/cordova/platform/check.js

This should not change anything regarding functionality just make the
code a _little_ more approachable and less horrible.
This was originally created during an effort to remove Q API usage.

Cleanup platform.check

---

src/cordova/plugin/remove.js

No functional changes. A by-product of debugging this module.

Make plugin.remove more easily understandable

---

integration-tests/platform.spec.js

Another episode in the series Spec Cleanup.
- Re-enable some tests
- Remove some tests for being duplicates after recent refactors
- Slightly reduced overall runtime
- Uniform, increased timeouts to address CI-3 of #642

platform.spec cleanup

---

spec/cordova/platform/addHelper.spec.js

This fixes the `cordova/platform/addHelper` tests that were previously attempted to fix in #636. This time I was able to fix the test double setup without having to modify any files from `src/`.
Contains a tiny bit of cleanup in the test-double-setup department too.
@brodybits You already reviewed this in #636. Would you care to see if you are fine with the new solution I have come up with?
Also part of #642.

Fix `cordova/platform/addHelper` tests

---

package.json

Was not found earlier, since it is "used" in our test fixtures.

Remove unused dependency properties-parser

---

package.json
src/plugman/fetch.js

Cherry-pick of #688 for 8.1.0 as discussed _and agreed_ in [[1]](https://lists.apache.org/thread.html/23b1a44a35b0bf58792ab2820230dac4236bdcab90573127bf7e91c6@%3Cdev.cordova.apache.org%3E)
[1] <https://lists.apache.org/thread.html/23b1a44a35b0bf58792ab2820230dac4236bdcab90573127bf7e91c6@%3Cdev.cordova.apache.org%3E>

CB-14166 distinguish npm.cmd and npm.exe in win32, to check if escape is necessary (workaround solution in 8.1.x only)

---

spec/plugman/install.spec.js

Due to failure in https://ci.appveyor.com/project/ApacheSoftwareFoundation/cordova-lib/build/1.0.1551/job/j0t3ymi9egbsk1co#L1400
Part of #642

Increase plugman/install test timeout

---

integration-tests/platform.spec.js

Due to local test timeout of test 009. Part of #642

Increase timeout for cordova.platform e2e tests

---

integration-tests/plugman_fetch.spec.js
src/plugman/fetch.js

All
Ensures that dependencies are properly copied when the source is a symlink/junction.
E2E test suite has been run and now finally passes on Windows.

Ensure local dependencies are properly copied on Windows

---

package.json
spec/hooks/Context.spec.js
src/hooks/Context.js

UPDATED:
- reintroduce `xcode` as needed in 8.1.x to avoid breaking plugins such as `branch-cordova-sdk` before next major release, to resolve GH-706 (bug #706)
- ~~emit a message in case someone uses `requireCordovaModule('xcode')` that it is now deprecated, will be removed in the near future, along with the recommended solution~~
- reintroduce some other dependencies to better ensure that any other plugins or applications using `requireCordovaModule` would not be broken by a minor release upgrade
- emit a deprecation warning message in case a plugin or application uses `requireCordovaModule` with a non-Cordova module
- some other updates from PR #707
This fix is NOT WANTED in `master` branch. I think we do not want to support `requireCordovaModule('xcode')` in the next major release. …

GH-706 dependency patch fix for 8.x only

---

spec/hooks/Context.spec.js
src/hooks/Context.js

Addresses the deprecation part of #689.

Deprecate `requireCordovaModule` for non-Cordova modules

---

package.json
spec/cordova/serve.spec.js
spec/helpers.js
src/cordova/serve.js

This is the last larger refactor that I needed/wanted to get done before tackling #681 and in turn #657.
I tried to keep the commits very focused to make the review easier. I also did manual testing of the server.

Test, fix and cleanup `cordova serve`

---

spec/helpers.js

`os.tmpdir()` on macOS returns `/var/folders`, but `/var` is a symlink to `/private/var`.
We dereference symlinks in a bunch of places, which was leading to tests failing when they expected something to get called with a path of `/var/folders/cordova-lib-whatever/...` and they were actually getting called with a path of `/private/var/folders/cordova-lib-whatever/...`.
This change ensures that when we create a temporary directory, we get the real path before we return it to the tests.
Ran tests of macOS and they all passed.

Fix 2 integration tests failures on macOS

---

spec/cordova/requirements.spec.js
src/cordova/requirements.js

Fixes #740.
All of them, I think.
Functions in utils.js expect to be called with `this` bound to the module. So this call crashed with an error
```
this.isCordova is not a function
```
This PR fixes the call to go through the proper binding.
It fixed my build. I also added a simple fail-before, pass-after unit test.

Fix crash in `cordova requirements` due to an unbound function

---

spec/cordova/platforms/platforms.spec.js
src/platforms/platformsConfig.json
src/plugman/util/default-engines.js

none
- Add Electron platform config and plugman default engine.
- Updated platform test spec to include Electron
- `npm t`

Add Electron Platform

---

src/plugman/fetch.js

The npm package name is already wrapped in quotes to prevent special characters from being execute. However the additional win32 code was further injecting quotes around the version causing npm to return a EINVALIDTAGNAME error. The win32 code is redundant and seems to not be required.
Windows, CLI
Fix plugin installation on windows platform
Ran it locally and error vanished

CB-14166: (cli) Fixed issue when installing plugins on windows

---

spec/hooks/Context.spec.js
src/hooks/Context.js

This includes a few changes to `hooks/Context` that necessitate a major release:
- Throw error if non-cordova module is required (Resolves #689)
- Remove outdated compatibility layer from 2015
- Lazily load `Context.cordova` to avoid cyclical dependency
- Use `const` for imports

Breaking changes in hooks/Context

---

src/plugman/util/metadata.js

This PR removes stale legacy handling code for files last created by Cordova 4.3.0.
The current version of the code transformed the old files to the new format and location, so removal of the current code should not affect any reasonably recent projects.
Since this is technically a breaking change, I thought it would be nice to include this into the upcoming major release.
I came across this when reviewing #680. 
I removed code that read `plugins/<PLUGIN>/.fetch.json` and integrated it into `plugins/fetch.json`.
I ran the existing test suite.

Remove handling of legacy .fetch.json files

---

src/cordova/prepare.js

all
Currently we're passing in an already-constructed ConfigParser instance as part of the fake projectInfo object, but the problem is that it's constructed with the version of cordova-common depended on by *cordova-lib* as opposed to the version of cordova-common depended on by the *platform*.
See https://github.com/apache/cordova-ios/issues/535 and https://github.com/apache/cordova-android/issues/690
Pass the path to the root config.xml in, so that we can construct the ConfigParser at the Platform API level, using the correct version.
In the meantime, for compatibility reasons, we have to keep passing in a ConfigParser instance, and the Platform API needs to handle the case where rootConfigXml is undefined and it needs to fetch the path out of the existing ConfigParser instance and then …

Pass project config.xml path to platform's prepare

---

integration-tests/pkgJson.spec.js
spec/cordova/platform/addHelper.spec.js
spec/cordova/platform/remove.spec.js
spec/cordova/plugin/add.spec.js
spec/cordova/plugin/remove.spec.js
spec/cordova/restore-util.spec.js
src/cordova/platform/addHelper.js
src/cordova/platform/remove.js
src/cordova/plugin/add.js
src/cordova/plugin/remove.js
src/cordova/restore-util.js

All (via tooling)
We've had one major version of cordova-lib that attempted to ensure both config.xml and package.json were kept in sync, and now it's time to push people more strongly towards using package.json.
We will still attempt to read values from config.xml and update them in package.json, but we will no longer reflect changes back to config.xml.
Whatever's saved in package.json should always have priority over what is read from config.xml.
The next phase will be to [improve the handling of package.json updates](https://github.com/apache/cordova-common/pull/34), and then in the next major to completely remove the code that looks at config.xml for platforms/plugins.
Updated spec and E2E tests.

Remove saving platforms/plugins to config.xml

---

src/plugman/install.js

All
Fixes #754
Fixes apache/cordova#52
Paths must not be wrapped in quotes before passing them to `fs`. When invoking commands on the shell, escaping should be handled by the shell library.
None. Opening PR here for CI.

Script path must not be wrapped in quotes

---

spec/cordova/restore-util.spec.js
src/cordova/restore-util.js
src/cordova/util.js

all
Some of the code removed in GH-750 had side effects on the rest of the plugin restoration procedure. Namely, despite wanting to migrate to package.json, we actually relied on config.xml for retrieving the plugin spec and variables. When we stopped syncing changes back to config.xml, those plugins stopped getting restored.
I've refactored this significantly to reduce complexity and make it easier to read and understand.
We look at package.json for plugins.
Then we look at config.xml. If a plugin exists in config.xml but not in package.json, we copy it to package.json.
Then we build up a list of the name/version/variables for each plugin, and pass them to the plugin installer in series.
All tests pass.
It appears to work properly, having been tested in several of my own apps now, but I …

Fix restoring plugins from package.json

---

integration-tests/plugin_fetch.spec.js
spec/cordova/plugin/add.getFetchVersion.spec.js
spec/cordova/plugin/add.spec.js

The logic in this test file was not very transparent and it relied on outdated fixtures.
I refactored the test to be more readable, robust and self contained. Finally I removed the reliance on the outdated fixtures and moved it to `spec` since it is actually a unit test.
`npm t`

Refactor plugin_fetch.spec

---

integration-tests/plugman_uninstall.spec.js
src/plugman/uninstall.js

In the old code, when `projectRoot` was falsy, `promise` was never waited upon.
The bug this fixes probably does not bite anyone in the wild, but it's a bug nonetheless (and it causes tests to be flaky). Maybe we can get it into the next patch release @dpogue?

Fix faulty Promise handling in plugman.uninstall

---

integration-tests/plugman_uninstall.spec.js

The stubbing is not actually needed for the tests. It actually caused problems after some refactoring I am currently working on, because the stubbing is not correct either. `ActionStack.prototype.process` actually has to return a `Q` instance when called from current `cordova-android`.
The tests that were using this stub still pass.

Remove unnecessary spy

---

spec/helper.js

Node.js throws an `Error` if the `error` event is emitted on a `EventEmitter` instance that has no handlers attached for it. This is usually the case during testing and often masks the actual error that is causing the issue.
We attach a listener to just log error events to console. During passing tests runs, no additional output is generated.

Prevent masking of errors during testing

---

src/plugman/createpackagejson.js

Right now `plugman createpackagejson <plugin dir>` reads values from `plugin.xml` in `<plugin dir>` but creates the `package.json` in `process.cwd()`. I could not find any documentation of this behavior, but I consider it a bug.
Always create the `package.json` in `<plugin dir>` next to `plugin.xml` instead.
Manual testing with plugman CLI and this version of lib.

Have plugman.createPackageJson create file in plugin dir, not in cwd

---

.eslintignore
src/plugman/init-defaults.js

`src/plugman/init-defaults.js` was not lintable since it was using the reserved word `package`.
Use the fact that the PromZard context is also provided as `this` to assign the `package` variable to `pkg` instead.
Manual testing with Plugman CLI.

Make src/plugman/init-defaults.js lintable

---

spec/cordova/platforms/platforms.spec.js
spec/cordova/util.spec.js
src/cordova/util.js

The logic in `cordova/util.getPlatformApiFunction` was a tad to complex and had a few problems because of that.
During testing I frequently had the situation that an error occurred during loading of a platform API module, mostly because of a missing dependency. This function caught these errors and insted threw an error claiming `'Your ' + platform + ' platform does not have Api.js'` which was plainly wrong and confusing.
On top of that came a dead code branch and IMHO unnecessary checks. Enough reason for a rewrite
AFAICT this method is not publicly exposed, so this should be a minor change at most.
- The happy path is unchanged as are the situations in which errors are thrown
- The second argument is now unused and could be removed at the call sites in a following or this PR
- The other …

Simpler and better cordova/util.getPlatformApiFunction

---

package.json

All
This update resolves the `npm audit` warning at this time.
see title: nyc@14 update in `devDependencies`
- ~~I added automated test coverage as appropriate for this change~~
- ~~Commit is prefixed with `(platform)` if this change only applies to one platform (e.g. `(android)`)~~
- ~~If this Pull Request resolves an issue, I linked to the issue in the text above (and used the correct [keyword to close issues using keywords](https://help.github.com/articles/closing-issues-using-keywords/))~~
- ~~I've updated the documentation if necessary~~

nyc@14 update in devDependencies

---

integration-tests/pkgJson.spec.js

This quick workaround is proposed in order to give us a green build as quickly as possible.
The build failure appeared when we reviewed and merged PR #783 but did *not* go away when I tried reverting it in PR #785.

Quick workaround for e2e failure on AppVeyor CI

---

src/plugman/install.js

All
When installing a plugin I got a non descript error message.
```sh
> cordova plugin add cordova-plugin-background-mode
Installing "cordova-plugin-background-mode" for android
warn
```
Running with `--verbose` cleared it up
The first parameter is the message.
Test for example with `cordova-plugin-background-mode` for android

output the error message if no engine has been defined

---

package.json
spec/plugman/variable-merge.spec.js
src/cordova/compile.js
src/cordova/emulate.js
src/cordova/platform/addHelper.js
src/cordova/prepare.js
src/cordova/run.js
src/plugman/fetch.js
src/plugman/install.js
src/plugman/uninstall.js
src/plugman/util/dependencies.js
src/plugman/variable-merge.js

Because we can. The only logical difference should be that `Object.assign` takes _own_ enumerable props, while `_.extend` enumerable.
Resolves #643

Replace underscore with modern JS

---

spec/cordova/prepare.spec.js
src/cordova/prepare.js

This remove s code that is commented with:
> CB-9987 We need to reinstall the plugins for the platform it they were added by cordova@<5.4.0
I'm unsure as to the kind of release this should go in. Since we probably officially removed support for cordova@<5.4.0, this should be non-breaking. If you want to be very strict, this would be breaking. Opinions?

Remove compatibility code for plugins added by cordova@<5.4.0

---

spec/cordova/util.spec.js
src/cordova/util.js

Nothing removed here was used anywhere in `cordova-lib`. Neither is the `cordova/util` module part of our public interface. Thus, all of the affected functions can be safely removed in any kind of release.

Remove unused exports from cordova/util

---

spec/cordova/emulate.spec.js

In some tests of `cordova/emulate.spec` it did call `cordova.run` or `cordova.compile` instead of `cordova.emulate`. This PR fixes this. In one case the expectations had to be adapted.
Additionally, this removes filtering of some outdated platform that does not exist anymore.

Fix cordova/emulate.spec

---

spec/cordova/build.spec.js
spec/cordova/emulate.spec.js
spec/cordova/platform/addHelper.spec.js
spec/cordova/plugin/add.spec.js
spec/cordova/plugin/remove.spec.js
spec/cordova/prepare.spec.js
spec/cordova/prepare/platforms.spec.js
spec/cordova/run.spec.js
spec/cordova/serve.spec.js
spec/plugman/install.spec.js
src/cordova/build.js
src/cordova/emulate.js
src/cordova/platform/addHelper.js
src/cordova/platform/list.js
src/cordova/plugin/add.js
src/cordova/plugin/remove.js
src/cordova/prepare.js
src/cordova/prepare/platforms.js
src/cordova/run.js
src/cordova/serve.js
src/cordova/util.js
src/platforms/index.js
src/platforms/platforms.js
src/plugman/install.js

Dependency cycles make testing hard since at least one module in the cycle has to require another at run-time. Furthermore they make it hard to separate the software into components conceptually. Finally, the facade-require anti-pattern that was often in use lead to huge parts of lib being loaded even is just a small part is actually being used (see also https://github.com/apache/cordova-cli/issues/406#issuecomment-481912178).
Details are in the commit messages.
After merging this PR, only one dependency cycle remains:
```
cordova/{prepare > restore-util > platform/index > platform/addHelper}
```
That's definitely the nastiest one, since it is the only one where there's also an actual cycle in the static call graph, i.e. a dependency cycle on function level instead of module level. I'll …

Break dependency cycles

---

src/cordova/util.js
src/plugman/install.js
src/plugman/uninstall.js

We should not have to spawn a child process to get a platform version. Since platform version scripts also export the version, we don't have to.
This would resolve the `maybeSpawn` issues in #812
Instead of running the version script, we require it (without caching).

Do not spawn child process to get platform version

---

integration-tests/plugin.spec.js

Removes leftover dead code, supposedly from before we let Jasmine handle Promises.

Remove dead code in integration-tests/plugin.spec

---

integration-tests/plugman_fetch.spec.js
spec/cordova/platform/addHelper.spec.js
spec/cordova/plugin/add.spec.js
spec/cordova/util.spec.js
spec/helpers.js
spec/plugman/util/metadata.spec.js

This is a revised version of all passing tests that were included in #602 or #680 respectively. I pulled them out of the original PR to reduce its volume and because they are valid without the other changes of the PR.
- Extend tests for addHelper.installPluginsForNewPlatform
- Simplify and extend unit tests for cordova/util.findPlugins
- Add passing unit tests for plugman/util/metadata
- Test plugin/add.getFetchVersion w/ scoped plugins
- Less strict path comparison in plugman_fetch.spec

Extend and improve plugin tests in preparation of supporting scoped plugins

---

src/cordova/plugin/index.js

none
Deprecates `plugin save`.
Adds warning emit that `plugin save` is deprecated and will be removed in next major.
closes: #778
- `npm t`

Deprecate plugin save command

---

package.json
spec/plugman/install.spec.js
src/cordova/info.js
src/cordova/plugin/util.js
src/cordova/targets.js
src/hooks/HooksRunner.js
src/plugman/install.js
src/plugman/uninstall.js

https://github.com/apache/cordova/issues/16
Replace `superspawn` usage with `execa` 
- `npm t`

chore: replace superspawn with execa

---

integration-tests/HooksRunner.spec.js
package.json
src/hooks/HooksRunner.js

Up until now, we have maintained code for shebang support in hook
scripts on Windows. Fortunately, execa comes with support for that out
of the box. So this commit drops our implementation and makes use of
execa's.

refactor: use execa's cross-platform shebang support in HooksRunner

---

integration-tests/plugin.spec.js
package.json
spec/cordova/fixtures/plugins/@cordova/plugin-test-dummy/package.json
spec/cordova/fixtures/plugins/@cordova/plugin-test-dummy/plugin.xml
spec/cordova/platform/addHelper.spec.js
spec/cordova/plugin/add.spec.js
spec/cordova/plugin/plugin_spec_parser.spec.js
spec/cordova/util.spec.js
spec/plugman/util/metadata.spec.js
src/cordova/platform/addHelper.js
src/cordova/plugin/add.js
src/cordova/plugin/plugin_spec_parser.js
src/cordova/util.js
src/plugman/install.js
src/plugman/uninstall.js
src/plugman/util/metadata.js

See #602 for details. Closes #680.
This contains the revised changes from #680 minus the changes from #818 and apache/cordova-common#94.
Only unit testing so far

Support scoped plugins

---

src/cordova/util.js

CI didn't re-run after merging in the new lint rules so I introduced some violations when I merged #821.

style: fix linting violations

---

integration-tests/HooksRunner.spec.js
integration-tests/plugin.spec.js

HooksRunner#12 did not actually test the HooksRunner class at all but
instead tested what arguments were passed to plugin (un)install hooks
would receive. Therefore it's a better fit for the plugin E2E tests.
The test code has been cleaned up in the process without making
essential changes to what is being tested.

test(e2e): re-enable HooksRunner#12 and move it to plugin#14

---

spec/fixture-helper.js

As it turned out that async `fs` methods are veeery slooow.

test: use fs.copySync for increased performance

---

integration-tests/pkgJson.spec.js
src/plugman/fetch.js

AFAICT, the check that is removed here was part of our previous plugin fetching mechanism and was not removed when migrating to cordova-fetch.
Fixes #795

fix: plugin installation from git url w/ semver

---

.eslintrc.yml
integration-tests/.eslintrc.yml
spec/.eslintrc.yml

* Centralize all configs into one file
* https://github.com/apache/cordova/issues/142
* Centralize Configs
* Added Apache Header to Config File.
- `npm run lint`

chore: consolidate eslint configs

---

integration-tests/HooksRunner.spec.js
integration-tests/plugman_fetch.spec.js
integration-tests/plugman_uninstall.spec.js
spec/cordova/build.spec.js
spec/cordova/compile.spec.js
spec/cordova/emulate.spec.js
spec/cordova/platform/addHelper.spec.js
spec/cordova/platform/getPlatformDetailsFromDir.spec.js
spec/cordova/platform/index.spec.js
spec/cordova/platform/remove.spec.js
spec/cordova/plugin/add.spec.js
spec/cordova/plugin/index.spec.js
spec/cordova/plugin/remove.spec.js
spec/cordova/prepare.spec.js
spec/cordova/run.spec.js
spec/cordova/serve.spec.js
spec/plugman/add_platform.spec.js
spec/plugman/create.spec.js
spec/plugman/install.spec.js

Make use of `expectAsync` (available since Jasmine 3.5) to check for expected rejections. This makes for shorter and clearer expectations
This also fixes a test that would otherwise break with https://github.com/apache/cordova-common/pull/121
Uses `expectAsync(...).toBeRejectedWithError(...)` and `expectAsync(...).toBeRejectedWith(...)` to replace rejection checking that was done with `fail()` before. Where it greatly improved readability I switched the tests to `async/await`.
`npm t`

test: use expectAsync for rejections

---

integration-tests/pkgJson.spec.js
integration-tests/platform.spec.js
integration-tests/plugin.spec.js
package.json
spec/cordova/util.spec.js
spec/fixture-helper.js
spec/project-test-helpers.js
src/cordova/util.js
src/platforms/platformsConfig.json

- Update Cordova dependencies to start using the next major releases.
- Use dependencies that fixed to the issues related to the combination of Node 12x+ and Rewire.
- Use the next major's patch nightlies (e.g: cordova-common) which contains bug fixes. This is to continue validating the fixes in the dependencies itself and identify if there are other issues to be resolved before pushing the next patch release for those dependencies.
- `npm t`

breaking: upgrade cordova dependencies for next major

---

package.json
spec/cordova/restore-util.spec.js
src/cordova/restore-util.js
src/util/promise-util.js

N/A
Closes #832 where the `cordova prepare` restore process would not look at package.json devDependencies for platforms, and would restore platforms with the wrong versions.
Make the platform restore process match the plugin restore process where both devDependencies and dependencies are taken into account.
This also includes fixes for writing package.json with the correct newlines, which should address the complaints raised in https://github.com/apache/cordova-cli/issues/353 and possibly https://github.com/apache/cordova-lib/issues/694.
It also changes the handling of promises when restoring platforms/plugins such that a failure to restore will return a rejecting promise rather than swallowing the error and continuing to build.
Unit tests pass

GH-832: Look at devDeps for restoring platforms

---

src/platforms/platformsConfig.json

Update iOS platform pinning to latest release 6.1.0
- `npm t`

chore(ios): update platform pinning to ^6.1.0

---

src/platforms/platformsConfig.json

Update OSX platform pinning to latest release 6.0.0
- `npm t`

chore(osx): update platform pinning to ^6.0.0

---

src/platforms/platformsConfig.json

Update Android platform pinning to latest release 9.0.0
- `npm t`

chore(android): update platform pinning to ^9.0.0

---

package.json

- Use short notation in `package.json`

chore: use short notation in package.json

---

package.json

This should have been part of #820

fix: remove unused dependency on cordova-create

---

spec/fixture-helper.js

This reverts an obsolete change from #833. Probably should have been part of #839.

test(fixture-helper): install android platform by name again

---

spec/cordova/platform/listDeprecated.spec.js

all
From work on PRs #851 and #852, I think the code to show which platforms are deprecated is not so well covered by testing. The following possible code mutation does not seem to trigger any test failures:
```diff
--- a/src/cordova/platform/list.js
+++ b/src/cordova/platform/list.js
@@ -58,7 +58,7 @@ function addDeprecatedInformationToPlatforms (platformsList) {
var platformKey = p.split(' ')[0]; // Remove Version Information
// allow for 'unknown' platforms, which will not exist in platforms
if ((platforms.info[platformKey] || {}).deprecated) {
-            p = p.concat(' ', '(deprecated)');
+            p = p.concat(' ', 'xxx');
}
return p;
});
```
Add `spec/cordova/platform/listDeprecated.spec.js` to test the output in case of any deprecated platforms.
The above mutation leads to …

unit test deprecated platforms

---

spec/helper.js

`true` is not a valid value for the `displayStacktrace` option of `jasmine-spec-reporter`. At least not anymore.

test: fix missing stack traces in jasmine output

---

spec/cordova/util.spec.js
src/cordova/util.js

The new mechanism introduced in #815 relied on all platforms exporting their version in their version script. This is not the case for the browser platform though. Thus we need to revert to spawning an external process for legacy platforms unfortunately.
For platforms that do not expose `Api.version`, synchronously call the version script instead.
I manually tested the new version with the current browser platform and `cordova info` output (which was broken for `browser` because of the bug fixed here)

fix(cordova/util): version detection for legacy platforms

---

integration-tests/pkgJson.spec.js

When `cordova-plugin-geolocation` introduced a new variable in v4.1.0, a test that expected it to have no variables started failing. 
However, whether there were any variables or not was beside the point of the test in the first place. It should only check that the key for the plugin is present in `cordova.plugins`.
I updated the test accordingly.
Fixes #863

test(pkgJson): fix test after release of geolocation plugin v4.1.0

---

integration-tests/pkgJson.spec.js

In some cases, npm 7 causes the `package.json` to look slightly different than with npm 6. This PR changes our tests so that they work with both flavors.
This PR addresses the following differences:
Saved GitHub URL format in `package.json`:
- npm 6: `git+https://github.com/apache/cordova-android.git#4.1.x`
- npm 7: `github:apache/cordova-android#4.1.x`
Empty devDependencies format in `package.json`:
- npm 6: `{}`
- npm 7: `undefined`
- Automated tests are passing with `npm@6`
- Automated tests are passing with `npm@^7.2` and https://github.com/apache/cordova-fetch/pull/91
_Except for one test that fails due to a bug in npm 7: https://github.com/npm/cli/issues/2339_

test(pkgJson): make expectations work for npm 5 to 7

---

src/cordova/requirements.js
src/cordova/serve.js

This removes usage of underscore that were introduced after merging #772.
Closes #869 
I rewrote the two remaining usages of underscore using plain JS.
Automated test suite

fix: remove undeclared dependency on underscore

---

README.md

Docs
The command to lint described in Readme file does not follow the changes introduced in #822.
Correct with `"lint"` NPM script like in _package.json_.
.

docs: correct linter command in Readme

---

spec/cordova/platform/addHelper.spec.js
src/cordova/platform/addHelper.js

Closes #866
"[Wrong platform version is detected when dependencies and devDependencies are both present](https://github.com/apache/cordova-lib/issues/866)"
Relates to:
"[Save platforms and plugins to devDependencies](https://github.com/apache/cordova-fetch/issues/64)"
All
The issue was discovered using a project which has both dev and normal dependencies where platform dependency was specified under `devDependencies`.
Steps to recreate:
1. Have a project with both dev and normal dependencies in `package.json`.
2. `cordova platform add electron@2.0.0`
3. `rm -rf ./node_modules ./plugins ./platforms`
4. `cordova prepare electron`
5. Should be using 2.0.0 from `package.json` but will be using 1.0.0 opinned version. 
This is a small fix to address an issue where Cordova CLI restores platforms …

fix: Platforms restored from both dev and normal dependencies.

---

spec/cordova/restore-util.spec.js
src/cordova/restore-util.js

All
Fixes #878 
Try platform name prefixed with `cordova-` for platform / spec mapping, before falling back to plain platform name.
Added a unit test to ensure that platforms are restored without config.xml engine entry, and from devDependency.
All existing unit tests passes.
Manually tested in a [repo project](https://github.com/lirichard/cordova-platform-devdependencies-reproduction).

fix(restore-util): consider long and short names when restoring platforms from package.json

---

package-lock.json
package.json

All
Note, all changes are backwards compatible.
When adding XML attributes to the XML tags, we currently need to update around 6 repos (cordova-common, cordova-lib, cordova-cli, platform repos, docs).
cordova-common 4.1.0 (https://github.com/apache/cordova-common/pull/181) fixes this by passing through all XML attributes. 
In order for platforms to begin using cordova-common 4.1.0, the developer's cordova-cli must use cordova-common 4.1.0.
cordova-cli depends on cordova-lib and cordova-common.
cordova-lib depends on cordova-common.
In order to ensure cordova-cli is always using the correct version of cordova-common, it would be safest to update cordova-lib first.
This PR updates cordova-lib's cordova-common to 4.1.0.
I've added unit tests for XML passthrough in cordova-common.
I've ran …

feat: bump cordova-common@4.1.0

---

package-lock.json

n/a
Update development related file, `package-lock.json`.
Remove any possible npm vuln notifications that comes from installing locked packages.  
- Rebuilt `package-lock.json`
n/a

chore: rebuild package-lock.json

---

package-lock.json
package.json
spec/cordova/util.spec.js

n/a
- Use latest npm packages where acceptable.
Bumped following packages:
* `fs-extra@^11.1.0`
* `write-file-atomic@^5.0.0`
* `cordova-android@^11.0.0`
* `jasmine@^4.5.0`
* `jasmine-spec-reporter@^7.0.0`
* `rewire@^6.0.0`
* `init-package-json@^4.0.1`
Packages not bumped due to ESM requirement:
* `detect-indent`
* `detect-newline`
* `execa`
* `globby`
* `pify`
This PR also bumped the node engine requirement to `>=16.13.0`. Some of the sub packages requires node 16 starting at this minor release.
Since this PR is for next major, it is safe to update the node requirement.
n/a

dep(npm): bump all dependencies to next major

---

spec/cordova/platforms/platforms.spec.js
src/platforms/platformsConfig.json

osx, windows
Remove OSX and Windows platform.
Since it was deprecated, this prepares the removal.
- n/a
- was already deprecated.

feat!: remove osx & windows platform

---

src/cordova/run.js
src/cordova/targets.js

n/a
Prepare for the removal of calling binaries in the platform packages. 
Use the platform API to handle listing out of targets.
This PR will call `platformApi.listTargets` when the platfrom api contains the method.
To also support platforms that has not been updated, it will fallback and call the old binrary.
`npm t`

feat!(run): call platform api to list targets

---

spec/cordova/platform/addHelper.spec.js
src/cordova/platform/addHelper.js

n/a
Fix installing platforms with tarball.
`cordova platform add cordova platform add ../cordova-android-12.0.0.tgz` will append `@latest` to the end and causes install failures.
Only append `@latest` to only platforms that are known.
`npm t`

fix: platform add with tarball

---

spec/cordova/platform/addHelper.spec.js
src/cordova/platform/addHelper.js

Any
Different installation orders for currently installed plugins
iOS
https://github.com/MaximBelov/reproduce-cordova-apply-plugins-sort/blob/20ab95bca8aef992aa5b1982b38e5e6d750580a8/plugins/ios.json
Android
https://github.com/MaximBelov/reproduce-cordova-apply-plugins-sort/blob/20ab95bca8aef992aa5b1982b38e5e6d750580a8/plugins/android.json
Plugins installation order should be the same for any platform and have the source of faithful from package.json
Why is this important?
ios: Prevent mix build phases
The plugin `cordova-plugin-firebasex` runs a hook that adds a new Build Phase "Crashlytics", which should be the last one
https://github.com/dpa99c/cordova-plugin-firebasex/pull/897
How to reproduce
https://github.com/MaximBelov/reproduce-cordova-apply-plugins-sort
How to reproduce …

fix(ios): Prevent mix build phases

---

src/cordova/plugin/remove.js

CLI - adding and removing plugins with differing required variables per platform (e.g. [cordova-plugin-googleplus](https://github.com/TheAnkurPanchani/cordova-plugin-googleplus) )
resolves apache/cordova-cli#578 :
`cordova plugin rm plugin-package --variable "IOS_ONLY_REQUIRED_VARIABLE=variable-value"` will fail if the project includes e.g. both android and ios platforms.
In `removePluginFromPlatform()`, at [cordova/plugin/remove.js:105](https://github.com/apache/cordova-lib/blob/7f8b2d011dc05749cf6075fe483b5e1bb08f1a07/src/cordova/plugin/remove.js#L105), `opts.cli_variables` is destructively reassigned to the result of `mergeVariables()`. As mergeVariables() selects only keys specified for a specific platform, this can result in CLI-specified values being lost before the platform that …

[cordova-cli #578] plugin/remove.js: don't stomp opts.cli_variables in removePluginFromPlatform()

---

spec/plugman/install.spec.js
src/cordova/platform/addHelper.js
src/plugman/install.js

n/a
- Support installing plugins to all prerelease identifiers as long as it still satisfies with semver.
- Improve the warning of installing a prerelease platform for all prerelease identifiers.
- Use `semver` to detect if the platform is a prerelease instead of using regular expression against specific tags.
- Update `semver.satisfies` to include prerelease version. This allows plugins to install on prerelease platforms as long as the platform's version still satisfies with the minimum version.
- `cordova platform add`
- `cordova plugin add`

fix: platform & plugin prerelease package support

---

.github/workflows/ci.yml
.github/workflows/release-audit.yml

all
Improve CI.
* Fix errors when dependabot PRs try to run tests in CI
* Ran in CI, tests pass

chore(ci): Fix failing dependabot PRs

---

src/plugman/fetch.js

We have a monorepo that contains a cordova application and a Cordova plugin. When adding the plugin to the applicatoin the `fetch.json` contains an absolute directory which does not work on other computers.
Persist a relative directory on disk instead of an absolute directory.
We have had the following patch in production for the last 2 months.
<details>
<summary>Patch</summary>
```diff
diff --git a/node_modules/cordova-lib/src/plugman/fetch.js b/node_modules/cordova-lib/src/plugman/fetch.js
index ec73836..2e4d1e2 100644
--- a/node_modules/cordova-lib/src/plugman/fetch.js
+++ b/node_modules/cordova-lib/src/plugman/fetch.js
@@ -84,7 +84,7 @@ function fetchPlugin (plugin_src, plugins_dir, options) {
pinfo: pluginInfoProvider.get(directory),
fetchJsonSource: {
type: 'local',
- …
```

Persist relative paths on disk

---

spec/cordova/plugin/add.spec.js
src/cordova/platform/addHelper.js
src/cordova/platform/remove.js
src/cordova/plugin/add.js
src/cordova/plugin/remove.js

Cordova removes the final new line in a package.json when running cordova commands. This causes us a problem since we have a formatting rule for final new lines.
Apply the same writing rules every time the package.json is written to.
We have had the following patch in production for the last 3 months.
<details>
<summary>Patch</summary>
```diff
diff --git a/node_modules/cordova-lib/src/cordova/platform/addHelper.js b/node_modules/cordova-lib/src/cordova/platform/addHelper.js
index 0856245..653f834 100644
--- a/node_modules/cordova-lib/src/cordova/platform/addHelper.js
+++ b/node_modules/cordova-lib/src/cordova/platform/addHelper.js
@@ -27,6 +27,9 @@ const cordova_util = require('../util');
const promiseutil = require('../../util/promise-util');
const platforms = require('../../platforms'); …
```

Keep final new line in package.json

---

.github/workflows/ci.yml
package-lock.json
package.json

N/A
node < 20 are already EOL.
- Upgrade node to 20.17.0
- Bump node modules:
- cordova-common
- init-package-json
- semver
- write-file-atomic
- @cordova/eslint-config
- jasmine
- nyc
- rewire
- Update packages by npm update
NOTE:
- Below modules could not be updated because it switched commonjs to esm from next version:
- detect-indent 
- detect-newline
- exec
- globby
- `nyc` should be replaced with `c8` but separate from this PR.
- Latest version of `init-package-json` requires `node@^20.17.0 || >= 22.9.0` so that I bump node to 20.17.0. It might be better to choose same requirement or `20.5.0`.
- npm t

chore!: bump node requirement & npm dependencies

---

licence_checker.yml
package-lock.json
package.json
src/plugman/install.js
src/plugman/util/dep-graph.js
src/plugman/util/dependencies.js

n/a
Remove `dep-graph` dependency
- Remove [`dep-graph`](https://www.npmjs.com/dep-graph) dependency.
- The last release was **2012**.
- Its repository was archived in 2018.
- It had a dependency on `underscore@1.2.1`.
In replacement of `dep-graph`, this PR would create our own custom class to behave identical.
- `npm t`
- All tests are passing and the coverage of the new class is 100%

feat: replace dep-graph dependency w/ custom class
